/odometry_aligner_node:
  ros__parameters:
    main_odom:
      input_topic: /Odometry/fastLioOdom
      min_samples: 1000
      use_position: true
      use_orientation: false

    aux_odoms:
      _0:
        input_topic: /Odometry/orbSlamOdom
        output_topic: /Odometry/aligned/orbSlamOdom
        registrator: lsq_2d_rotation_uniform_scaling
        min_samples: 1000
        use_position: true
        use_orientation: false